### ISSUE TITLE
Todo list for 0.3.0 release

### ISSUE THREAD

**Issue by bergos** [rdf-ext/rdf-ext#46]
- [x] create modules for all [parsers and serializers](https://github.com/rdf-ext/rdf-ext/issues/36)
  - [x] create module for [JSON-LD parser](https://github.com/rdf-ext/rdf-parser-jsonld)
  - [x] create module for [JSON-LD serializer](https://github.com/rdf-ext/rdf-serializer-jsonld)
  - [x] create module for [Microdata parser](https://github.com/rdf-ext/rdf-parser-microdata)
  - [x] create module for [N-Triples serializer](https://github.com/rdf-ext/rdf-serializer-ntriples)
  - [x] create module for [RDF/XML parser](https://github.com/rdf-ext/rdf-parser-rdfxml)
  - [x] create module for [SPARQL update serializer](https://github.com/rdf-ext/rdf-serializer-sparql-update)
  - [x] create module for [Turtle/N3 parser](https://github.com/rdf-ext/rdf-parser-n3)
  - [x] create module for [Turtle/N3 serializer](https://github.com/rdf-ext/rdf-serializer-n3)
- [ ] create modules for all stores with new interface
  - [x] create module for [in memory store](https://github.com/rdf-ext/rdf-store-inmemory)
  - [x] create module for [SPARQL store](https://github.com/rdf-ext/rdf-store-sparql)
  - [x] create module for [LDP store](https://github.com/rdf-ext/rdf-store-ldp)
  - [ ] create module for [file system store](https://github.com/rdf-ext/rdf-store-fs)
  - [x] create module for [single graph store](https://github.com/rdf-ext/rdf-store-singlegraph)
  - [x] create module for [abstract store](https://github.com/rdf-ext/rdf-store-abstract)
- [x] create module for [Clownface](https://github.com/rdf-ext/clownface)
- [ ] add documentation
  - [ ] for abstract parser
  - [ ] for abstract serializer
  - [ ] for abstract store
- [ ] implement distribution builder

**Comment by bergos** [comment]
This issue was moved to rdf-ext/discussions#15
